[pytest]
minversion = 7.0
addopts = -v "--pdbcls=IPython.terminal.debugger:Pdb"
testpaths =
    tests
markers =
    requires(*modules): skip test if one or more Python modules are not installed
    torch: tests requiring torch, automatically skipped if torch is not installed and user did not request it explicitly.
    cupy: tests requiring cupy, automatically skipped if cupy is not installed and user did not request it explicitly.
    jax: tests requiring jax, automatically skipped if jax is not installed and user did not request it explicitly.
    cuda: tests requiring CUDA support
