[pytest]
minversion = 7.0
addopts = -v "--pdbcls=IPython.terminal.debugger:Pdb"
testpaths =
    tests
markers =
    requires(*modules): skip test if one or more Python modules are not installed
    torch: tests requiring torch
    cupy: tests requiring cupy
    jax: tests requiring jax
    cuda: tests requiring CUDA support
