channels:
- conda-forge
- nodefaults
dependencies:
- array-api-compat
- earthkit-data
- make
- mypy
- myst-parser
- nbsphinx
- pandas-stubs
- pint
- pip
- pre-commit
- pytest
- pytest-cov
- sphinx
- sphinx-autoapi
- sphinx-rtd-theme
- xarray
name: earthkit-utils

